Ei nextjs pages
oslabs-beta/notikube pull request #21
Opened 2024-01-18 03:16 UTC by DeveloperIkhalea

## Overview

**Issue Type**

- [ ] Bug
- [x] Feature
- [ ] Tech Debt
- [ ] Docs
- [ ] Other

**Description**
A clear and concise description of the issue.
Created a ui folder and putting the code for the sidebar components, and also restructured the landing page and its components.
**Ticket Item**

**Figma link - optional**
**Spec link - optional**

**Steps to Reproduce Bug / Validate Feature / Confirm Tech Debt Fix**

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Previous behavior**
A clear and concise description of what was originally happening.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots & Videos**
If applicable, add screenshots and videos to help explain your issue type.

**Additional context**
Add any other context about the problem here.

2024-01-18 03:37 UTC, jesse-chou approved these changes
Looks good to me. Thanks Emmanuel

2024-01-20 18:17 UTC, derekcoughlan reviewed
Thanks Emmanuel! Just a few questions for you.

2024-01-20 18:17 UTC, derekcoughlan commented on app/dashboard/Test/page.tsx
@DeveloperIkhalea - What is this page?

2024-01-20 18:17 UTC, derekcoughlan commented on app/dashboard/layout.tsx
@DeveloperIkhalea is {children} not needed in this page? Do the children within this layout render properly?

2024-01-20 18:17 UTC, derekcoughlan commented on app/dashboard/profile/page.tsx
@DeveloperIkhalea What is the profile page?

2024-01-20 23:25 UTC, jesse-chou requested changes
Changes needed. Format riles

2024-01-20 23:49 UTC, derekcoughlan approved these changes
Thanks!

2024-01-20 23:49 UTC, jesse-chou approved these changes
Thanks for the changes Emmanuel.

2024-01-20 23:50 UTC, merged